<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
	<parent>
		<groupId>io.github.sokybot</groupId>
		<artifactId>sokybot</artifactId>

		<version>1.0-SNAPSHOT</version>
	</parent>

	<modelVersion>4.0.0</modelVersion>

	<artifactId>sokybot-api</artifactId>
	<packaging>bundle</packaging>
	<name>sokybot-api</name>
    <properties>
        <spring-boot.version>2.7.13</spring-boot.version>
        <lombok.version>1.18.30</lombok.version>
    </properties>


	<dependencies>
		<dependency>
			<groupId>org.slf4j</groupId>
			<artifactId>slf4j-api</artifactId>
            <version>1.7.36</version>
		</dependency>
	<!-- https://mvnrepository.com/artifact/javax.persistence/javax.persistence-api -->
	<dependency>
		<groupId>javax.persistence</groupId>
		<artifactId>javax.persistence-api</artifactId>
		<version>2.2</version>
	</dependency>
        <dependency>
            <groupId>org.hibernate</groupId>
            <artifactId>hibernate-core</artifactId>
            <version>5.6.15.Final</version>
        </dependency>
        <dependency>
            <groupId>org.projectlombok</groupId>
            <artifactId>lombok</artifactId>
            <version>${lombok.version}</version>
            <scope>provided</scope>
        </dependency>
        <dependency>
            <groupId>org.springframework.boot</groupId>
            <artifactId>spring-boot-starter</artifactId>
             <version>${spring-boot.version}</version>
        </dependency>
        <dependency>
            <groupId>org.springframework.data</groupId>
            <artifactId>spring-data-jpa</artifactId>
            <version>2.7.13</version>
        </dependency>

        <dependency>
			<groupId>org.orbisgis</groupId>
			<artifactId>poly2tri-core</artifactId>
			<version>0.1.2</version>
		</dependency>
		<dependency>
            <groupId>org.springframework.statemachine</groupId>
            <artifactId>spring-statemachine-core</artifactId>
            <version>2.5.1</version>
        </dependency>
		<dependency>
			<groupId>${project.groupId}</groupId>
			<artifactId>sokybot-pk2</artifactId>
			<version>${project.version}</version>
		</dependency>
		<dependency>
			<groupId>${project.groupId}</groupId>
			<artifactId>sokybot-security</artifactId>
			<version>${project.version}</version>
		</dependency>
		<dependency>
			<groupId>${project.groupId}</groupId>
			<artifactId>sokybot-persistence</artifactId>
			<version>${project.version}</version>
			<scope>provided</scope>
		</dependency>
	</dependencies>

	<build>
		<plugins>
			<plugin>
				<groupId>org.apache.felix</groupId>
				<artifactId>maven-bundle-plugin</artifactId>
				<extensions>true</extensions>
				<configuration>
					<instructions>
						<Bundle-SymbolicName>${project.artifactId}</Bundle-SymbolicName>
						<Import-Package>*;resolution:=optional</Import-Package>
						<Export-Package>
						org.sokybot.*,
						org.sokybot.api.events,
						picocli.*
					</Export-Package>
					</instructions>
				</configuration>
			</plugin>
		</plugins>
	</build>
</project>