<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>
    
    <parent>
        <groupId>org.sokybot</groupId>
        <artifactId>sokybot</artifactId>
        <version>1.0-SNAPSHOT</version>
        <relativePath>../../pom.xml</relativePath>
    </parent>

    <artifactId>sokybot-engine-api</artifactId>
    <packaging>bundle</packaging>
    
    <dependencies>
        <dependency>
            <groupId>${project.groupId}</groupId>
            <artifactId>sokybot-proxy</artifactId>
            <version>${project.version}</version>
            <scope>provided</scope>
        </dependency>
        <dependency>
            <groupId>${project.groupId}</groupId>
            <artifactId>sokybot-settings</artifactId>
            <version>${project.version}</version>
            <scope>provided</scope>
        </dependency>
        <dependency>
            <groupId>${project.groupId}</groupId>
            <artifactId>sokybot-game-model</artifactId>
            <version>${project.version}</version>
            <scope>provided</scope>
        </dependency>
    </dependencies>

    <build>
        <plugins>
            <plugin>
                <groupId>org.apache.felix</groupId>
                <artifactId>maven-bundle-plugin</artifactId>
                <extensions>true</extensions>
                <configuration combine.self="override">
                    <instructions>
                        <Bundle-SymbolicName>${project.groupId}.${project.artifactId}</Bundle-SymbolicName>
                        <Bundle-Name>${project.name}</Bundle-Name>
                        <Bundle-Version>${project.version}</Bundle-Version>
                        <Bundle-Description>${project.description}</Bundle-Description>
                        <Export-Package>
                            org.sokybot.engine,
                            org.sokybot.engine.api,
                            org.sokybot.engine.api.behavior,
                            org.sokybot.engine.api.event,
                            org.sokybot.engine.api.extension,
                            org.sokybot.engine.api.handler,
                            org.sokybot.engine.api.workflow,
                            org.sokybot.engine.api.*
                        </Export-Package>
                        <Import-Package>
                            !com.aayushatharva.brotli4j,
                            !com.aayushatharva.brotli4j.*,
                            org.sokybot.proxy.*;version="[1.0,2)",
                            org.sokybot.settings.*;version="[1.0,2)",
                            org.sokybot.gamemodel.*;version="[1.0,2)",
                            *;resolution:=optional
                        </Import-Package>
                    </instructions>
                </configuration>
            </plugin>
        </plugins>
    </build>
</project>
