<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>
    <parent>
        <groupId>org.sokybot</groupId>
        <artifactId>sokybot</artifactId>
        <version>1.0-SNAPSHOT</version>
        <relativePath>../pom.xml</relativePath>
    </parent>
    
    <artifactId>sokybot-network-aggregator</artifactId>
    <packaging>pom</packaging>
    <name>Sokybot :: Network</name>
    <description>Network proxy and security components</description>
    
    <modules>
        <module>sokybot-packet-sniffer-api</module>
        <module>sokybot-proxy</module>
        <module>sokybot-security</module>
        <module>sokybot-packet-sniffer</module>
    </modules>
</project>
