<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>
    <parent>
        <groupId>org.sokybot</groupId>
        <artifactId>sokybot</artifactId>
        <version>1.0-SNAPSHOT</version>
        <relativePath>../pom.xml</relativePath>
    </parent>
    
    <artifactId>sokybot-core-aggregator</artifactId>
    <packaging>pom</packaging>
    <name>Sokybot :: Core</name>
    <description>Core engine and runtime components</description>
    
    <modules>
        <module>sokybot-engine</module>
        <module>sokybot-engine-api</module>
        <module>sokybot-runtime</module>
        <module>sokybot-behaviors-training</module>
        <module>sokybot-login-policies-builtin</module>
        <module>sokybot-login-protocol-builtin</module>
        <module>sokybot-login-settings-builtin</module>
        <module>sokybot-login-security-builtin</module>
        <module>sokybot-login-workflow-builtin</module>
        <module>sokybot-trade-coordination-api</module>
        <module>sokybot-trade-coordinator</module>
        <module>sokybot-behaviors-trade</module>
        <module>sokybot-combat-api</module>
        <module>sokybot-navigation-api</module>
        <module>sokybot-behaviors-combat</module>
        <module>sokybot-town-api</module>
        <module>sokybot-behaviors-town</module>
        <module>sokybot-pet-api</module>
    </modules>
</project>
